### ISSUE TITLE
Not specifying column metadata bounds leaves a column with no noise applied.

### ISSUE THREAD

**Issue by gregaw** [opendifferentialprivacy/smartnoise-sdk#317]
To reproduce 
- create a table with two columns and the following smartnoise metadata:
```
col:
  ? ''
  : table:
      duration:
        type: float
      id:
        private_id: true
        type: int
      max_ids: 1
      row_privacy: false
      rows: 1000
      sample_max_ids: true
engine: pandas
```

- run multiple queries summing and averaging the `duration` column

The problem:
- noise gets applied to the AVG queries, but doesn't to the SUM queries (see the attached image)

The reason:
- sensitivity for the `duration` column is set to `None` and disables the noise mechanism
- `AVG` works only because the noise for `COUNT` is hardcoded to `1`.

![image](https://user-images.githubusercontent.com/361951/100630889-653c6800-332b-11eb-9603-5e4e02ae1484.png)
